### PR TITLE
Geni jaho bugfix/UI improvements

### PR DESCRIPTION
**Pull request by xlcrr**

### CODE REVIEW

**Comment by xlcrr** [comment]
3 things left to do here @GeniJaho 

1. When the user clicks a tag from global search, it should add the tag.
2. Clear the input
3. Reset the search

**Comment by GeniJaho** [comment]
> 3 things left to do here @GeniJaho
> 
> 1. When the user clicks a tag from global search, it should add the tag.
> 2. Clear the input
> 3. Reset the search

So it should act identically to the Add Tag button?

**Comment by xlcrr** [comment]
Yes, as soon as the click the suggestion, add the tag

**Comment by GeniJaho** [comment]
I added the selected tag when a user selects an option from the global search.
Also, when the page first loads, now the search is on focus, and you can start typing directly.

**Pull request merged**
