### PR TITLE
improved /tag UI/UX

### PR DESCRIPTION
**Pull request by jshepin**
- removed confusing UI elements that are not needed
- added svg icons
- removed distracting background
- generally cleaned up the ui a bit

### CODE REVIEW

**Comment by jshepin** [comment]
Many changes were made under my discretion. If you disagree with any of the UI changes, please let me know and I will change them. As a new user to the site, I was quite confused by some of the ui elements on the /tag page, and changed it to how I would have wanted it to look like. Again, feel free to disagree. Thanks - Joseph

**Comment by jshepin** [comment]
image

Changes/reasoning:
Removed "previous/next image" buttons. - The pagination buttons are already there to move to different images. Images should be uploaded when complete and it encourages people to click "upload" instead of "next", reducing confusion as to what you should do.

Removed  "Total images uploaded:" number - You can easily see how many pictures you uploaded in your profile. It is also not relavent in  /tag 

Removed "Images left to tag" - you can easily see this number in the pagination buttons. 

Removed photo # and datetime information at the top - this is also irrelevant information for image tagging.

**Comment by jshepin** [comment]
image

**Comment by jshepin** [comment]
image

**Comment by jshepin** [comment]
also, I will switch out those SVG's with the font awesome logos.

**Comment by xlcrr** [comment]
Too many changes were, some are okay, but some are not. We will refactor this soon once I give instructions on what needs to be done

**Pull request closed without merging**
