### PR TITLE
feature/improve-ui-for-about-page

### PR DESCRIPTION
**Pull request by lhtrung307**
Improve mobile and desktop UI for about page

### CODE REVIEW

**Comment by xlcrr** [comment]
Can you provide screenshots? Also that 100vh is a global setting. Did you check for unintended consequences?

**Comment by lhtrung307** [comment]
It's a long page, you should check it. And I've checked for 100vh.

**Comment by xlcrr** [comment]
Can anyone else take a look at this? It would help

**Comment by xlcrr** [comment]
Doesn't look good for me. Am I missing something?

Screenshot 2021-01-17 at 15 45 13

**Comment by xlcrr** [comment]
Screenshot 2021-01-17 at 15 46 06

This should also be positioned absolutely on the bottom-right of the map, and it should stay there as we change the size of the browser window

**Pull request closed without merging**
