### PR TITLE
telescope implementation

### PR DESCRIPTION
**Pull request by kevinmakwana**

### CODE REVIEW

**Review by xlcrr — APPROVED** [review]

**Comment by xlcrr** [comment]
Awesome! Let's try it.

Can you merge `staging` into this PR and fix errors? Then we can merge it

Otherwise I can do it ~ Friday

**Comment by xlcrr** [comment]
@kevinmakwana can you fix this composer merge conflict please?

**Comment by kevinmakwana** [comment]
@xlcrr Yes sure

**Comment by kevinmakwana** [comment]
@xlcrr Conflicts resolved.

**Pull request merged**
